const mongoose = require('mongoose');
const dotenv = require('dotenv');
const User = require('./models/User');
const Product = require('./models/Product');
const Order = require('./models/Order');
dotenv.config();
const users = [
  {
    name: 'Admin User',
    email: 'admin@example.com',
    password: 'password123',
    role: 'admin',
  },
  {
    name: 'Test User',
    email: 'user@example.com',
    password: 'password123',
    role: 'user',
  },
];
const products = [
  {
    name: 'Omega Speedmaster Professional',
    price: 432000,
    description: 'The legendary Moonwatch. Hand-wound mechanical chronograph, the first watch worn on the Moon. Co-Axial Master Chronometer certified.',
    images: ['/watch-img/Omega Speedmaster Professional.jpg'],
    category: 'Mechanical',
    brand: 'Omega',
    countInStock: 3,
    rating: 4.8,
    numReviews: 22,
  },
  {
    name: 'Seiko Presage Cocktail Time',
    price: 29000,
    description: 'Stunning enamel sunburst dial inspired by Japanese cocktail bars. Automatic movement with 41-hour power reserve.',
    images: ['/watch-img/Seiko Presage Cocktail Time.jpg'],
    category: 'Mechanical',
    brand: 'Seiko',
    countInStock: 10,
    rating: 4.6,
    numReviews: 15,
  },
  {
    name: 'Tissot Le Locle Powermatic 80',
    price: 38500,
    description: 'Swiss-made dress watch with 80-hour power reserve. Elegant guilloche dial, sapphire crystal, heritage design.',
    images: ['/watch-img/Tissot Le Locle Powermatic 80.jpg'],
    category: 'Mechanical',
    brand: 'Tissot',
    countInStock: 7,
    rating: 4.5,
    numReviews: 19,
  },
  {
    name: 'Apple Watch Ultra 2',
    price: 89900,
    description: 'Precision dual-frequency GPS, depth gauge, 60-hour battery life. Titanium case with customisable Action Button. The ultimate adventure smartwatch.',
    images: ['/watch-img/Apple Watch Ultra 2.jpg'],
    category: 'Smart',
    brand: 'Apple',
    countInStock: 8,
    rating: 4.9,
    numReviews: 40,
  },
  {
    name: 'Samsung Galaxy Watch 6 Classic',
    price: 34999,
    description: 'Iconic rotating bezel, advanced sleep coaching, body composition analysis and BIA sensor. Sleek stainless steel finish.',
    images: ['/watch-img/Samsung Galaxy Watch 6 Classic.jpg'],
    category: 'Smart',
    brand: 'Samsung',
    countInStock: 12,
    rating: 4.5,
    numReviews: 28,
  },
  {
    name: 'Garmin Fenix 7X Solar',
    price: 74990,
    description: 'Solar-powered GPS multisport watch. Up to 37 days battery in smartwatch mode. Topographic maps and health monitoring.',
    images: ['/watch-img/Garmin Fenix 7X Solar.jpg'],
    category: 'Smart',
    brand: 'Garmin',
    countInStock: 5,
    rating: 4.7,
    numReviews: 17,
  },
  {
    name: 'Rolex Submariner Date',
    price: 875000,
    description: 'The quintessential diver\'s watch. Oystersteel case, waterproof to 300m, Cerachrom bezel insert. A timeless icon for every adventure.',
    images: ['/watch-img/Rolex Submariner Date.png'],
    category: 'For Him',
    brand: 'Rolex',
    countInStock: 2,
    rating: 5.0,
    numReviews: 18,
  },
  {
    name: 'TAG Heuer Carrera Chronograph',
    price: 262000,
    description: 'Iconic racing chronograph born on the circuit in 1963. Tachymeter scale, column-wheel movement, sapphire caseback.',
    images: ['/watch-img/TAG Heuer Carrera Chronograph.jpg'],
    category: 'For Him',
    brand: 'TAG Heuer',
    countInStock: 6,
    rating: 4.6,
    numReviews: 9,
  },
  {
    name: 'Casio G-Shock GA-2100',
    price: 8995,
    description: 'CasiOak — carbon core guard structure, shock-resistant, 200m water resistance. Slim profile, analog-digital display.',
    images: ['/watch-img/Casio G-Shock GA-2100.jpg'],
    category: 'For Him',
    brand: 'Casio',
    countInStock: 30,
    rating: 4.7,
    numReviews: 120,
  },
  {
    name: 'Cartier Tank Solo',
    price: 234000,
    description: 'Timeless icon of elegance. Rectangular pale champagne dial, blued-steel sword hands, Roman numerals. The ultimate women\'s dress watch.',
    images: ['/watch-img/Cartier Tank Solo.jpg'],
    category: 'For Her',
    brand: 'Cartier',
    countInStock: 5,
    rating: 4.9,
    numReviews: 30,
  },
  {
    name: 'Michael Kors Lexington Rose Gold',
    price: 18995,
    description: 'Glamorous rose gold-tone chronograph with mother-of-pearl dial and crystal-studded bezel. Effortlessly chic.',
    images: ['/watch-img/Michael Kors Lexington Rose Gold.jpg'],
    category: 'For Her',
    brand: 'Michael Kors',
    countInStock: 14,
    rating: 4.3,
    numReviews: 45,
  },
  {
    name: 'Titan Raga Viva',
    price: 6995,
    description: 'Delicate floral-inspired bracelet watch with diamond-cut case and a jewel-like aesthetic. Made for the modern Indian woman.',
    images: ['/watch-img/Titan Raga Viva.jpg'],
    category: 'For Her',
    brand: 'Titan',
    countInStock: 20,
    rating: 4.4,
    numReviews: 68,
  },
  {
    name: 'Timex Ironman Youth',
    price: 3799,
    description: 'Durable resin case, easy-read digital display, water-resistant to 50m. Indiglo backlight for night-time reading. Perfect for active kids.',
    images: ['/watch-img/Timex Ironman Youth.jpg'],
    category: 'For Kids',
    brand: 'Timex',
    countInStock: 25,
    rating: 4.4,
    numReviews: 55,
  },
  {
    name: 'Casio Baby-G BGA-280',
    price: 6495,
    description: 'Shock-resistant and water-resistant to 100m. Pastel colour palette, step counter, and world timer. Fun, sporty and tough.',
    images: ['/watch-img/Casio Baby-G BGA-280.jpg'],
    category: 'For Kids',
    brand: 'Casio',
    countInStock: 20,
    rating: 4.5,
    numReviews: 32,
  },
  {
    name: 'Fastrack Trendies',
    price: 1995,
    description: 'Sporty digital watch with bold OLED display, alarm, stopwatch and splash resistance. Available in neon-pop colours kids will love.',
    images: ['/watch-img/Fastrack Trendies.jpg'],
    category: 'For Kids',
    brand: 'Fastrack',
    countInStock: 35,
    rating: 4.2,
    numReviews: 88,
  },
  {
    name: 'Audemars Piguet Royal Oak',
    price: 2350000,
    description: 'The watch that redefined luxury. Iconic octagonal bezel with 8 hexagonal screws, integrated bracelet, Grande Tapisserie dial. In polished steel.',
    images: ['/watch-img/Audemars Piguet Royal Oak.jpg'],
    category: 'Luxury',
    brand: 'Audemars Piguet',
    countInStock: 1,
    rating: 5.0,
    numReviews: 7,
  },
  {
    name: 'Patek Philippe Calatrava',
    price: 2940000,
    description: 'The apex of horological craft. Ultra-thin movement, hand-finished three-body polished case, hobnail guilloché bezel. A wristwatch for generations.',
    images: ['/watch-img/Patek Philippe Calatrava.jpg'],
    category: 'Luxury',
    brand: 'Patek Philippe',
    countInStock: 1,
    rating: 5.0,
    numReviews: 4,
  },
  {
    name: 'IWC Portugieser Chronograph',
    price: 780000,
    description: 'Large 41mm stainless steel case, pulsometer scale, elegant ivory-colour dial. Column-wheel chronograph with lateral clutch. Swiss-made excellence.',
    images: ['/watch-img/IWC Portugieser Chronograph.jpg'],
    category: 'Luxury',
    brand: 'IWC',
    countInStock: 2,
    rating: 4.9,
    numReviews: 11,
  },
  {
    name: 'A. Lange & Söhne Lange 1',
    price: 3200000,
    description: 'Exquisite German craftsmanship. Featuring the signature outsize date, twin mainspring barrels for a 72-hour power reserve, and hand-engraved balance cock.',
    images: ['/watch-img/A. Lange & Söhne Lange.jpg'],
    category: 'Luxury',
    brand: 'A. Lange & Söhne',
    countInStock: 2,
    rating: 4.9,
    numReviews: 8,
  },
  {
    name: 'Blancpain Fifty Fathoms',
    price: 1150000,
    description: 'The pioneer of modern diving watches. Features a robust unidirectional sapphire bezel, black dial with luminescent markers, and 120-hour power reserve.',
    images: ['/watch-img/Blancpain Fifty Fathoms.jpg'],
    category: 'Mechanical',
    brand: 'Blancpain',
    countInStock: 3,
    rating: 4.8,
    numReviews: 12,
  },
  {
    name: 'Breguet Reine de Naples',
    price: 2800000,
    description: 'Stunning egg-shaped design inspired by the first wristwatch ever made. Features a mother-of-pearl dial, diamond-set bezel, and automatic movement.',
    images: ['/watch-img/Breguet Reine de Naples.jpg'],
    category: 'For Her',
    brand: 'Breguet',
    countInStock: 3,
    rating: 4.9,
    numReviews: 5,
  },
  {
    name: 'Breitling Navitimer B01',
    price: 680000,
    description: "The iconic pilot's chronograph. Features the famous circular slide rule bezel for flight calculations, Breitling Manufacture Caliber 01, and a distinct black dial.",
    images: ['/watch-img/Breitling Navitimer B01.jpg'],
    category: 'Mechanical',
    brand: 'Breitling',
    countInStock: 5,
    rating: 4.7,
    numReviews: 16,
  },
  {
    name: 'Bulova Lunar Pilot',
    price: 45000,
    description: 'Inspired by the watch worn during the Apollo 15 mission. Features a high-performance proprietary quartz movement with 262 kHz vibrational frequency.',
    images: ['/watch-img/Bulova Lunar Pilot.jpg'],
    category: 'For Him',
    brand: 'Bulova',
    countInStock: 8,
    rating: 4.6,
    numReviews: 24,
  },
  {
    name: 'Bvlgari Serpenti Tubogas',
    price: 850000,
    description: 'A true icon of design. Coiling single-spiral stainless steel bracelet with a curved case set with brilliant-cut diamonds, evoking the sinuosity of a snake.',
    images: ['/watch-img/Bvlgari Serpenti Tubogas.jpg'],
    category: 'For Her',
    brand: 'Bvlgari',
    countInStock: 4,
    rating: 4.8,
    numReviews: 14,
  },
  {
    name: 'Chopard Happy Sport',
    price: 580000,
    description: 'Elegant stainless steel case with signature free-spinning dancing diamonds floating above the silver-toned dial. A perfect blend of sport and glamour.',
    images: ['/watch-img/Chopard Happy Sport.jpg'],
    category: 'For Her',
    brand: 'Chopard',
    countInStock: 6,
    rating: 4.7,
    numReviews: 19,
  },
  {
    name: 'Flik Flak Spider-Man',
    price: 3500,
    description: 'Swiss-made watch designed to help kids learn to tell time. Shock-resistant, BPA-free, and machine washable fabric strap featuring Spider-Man.',
    images: ['/watch-img/Flik Flak Spider-Man.jpg'],
    category: 'For Kids',
    brand: 'Flik Flak',
    countInStock: 25,
    rating: 4.5,
    numReviews: 42,
  },
  {
    name: 'Garmin Bounce Smartwatch',
    price: 14990,
    description: "Kid's smartwatch with LTE connectivity for text/voice messaging, real-time location tracking, and step counters in a durable, swim-friendly design.",
    images: ['/watch-img/Garmin Bounce Smartwatch.jpg'],
    category: 'For Kids',
    brand: 'Garmin',
    countInStock: 15,
    rating: 4.4,
    numReviews: 21,
  },
  {
    name: 'Hublot Big Bang Original',
    price: 950000,
    description: 'The art of fusion. Features a black structured rubber strap, carbon dial, satin-finished ceramic bezel, and a chronograph self-winding movement.',
    images: ['/watch-img/Hublot Big Bang Original.jpg'],
    category: 'Luxury',
    brand: 'Hublot',
    countInStock: 2,
    rating: 4.7,
    numReviews: 11,
  },
  {
    name: 'Jaeger-LeCoultre Reverso Tribute',
    price: 790000,
    description: 'Classic art deco style with the signature swivelling rectangular case. Monoface design with a stunning blue sunray dial and manual-winding movement.',
    images: ['/watch-img/Jaeger-LeCoultre Reverso Tribute.jpg'],
    category: 'Luxury',
    brand: 'Jaeger-LeCoultre',
    countInStock: 3,
    rating: 4.8,
    numReviews: 13,
  },
  {
    name: 'Longines HydroConquest',
    price: 155000,
    description: 'High-performance diving watch featuring a ceramic bezel, automatic movement, 300m water resistance, and a double safety folding clasp.',
    images: ['/watch-img/Longines HydroConquest.jpg'],
    category: 'For Him',
    brand: 'Longines',
    countInStock: 8,
    rating: 4.6,
    numReviews: 22,
  },
  {
    name: 'Orient Kamasu',
    price: 22000,
    description: 'Popular Japanese diver with in-house automatic movement, sapphire crystal, and day-date display. 200m water resistance with dark green dial.',
    images: ['/watch-img/Orient Kamasu.jpg'],
    category: 'Mechanical',
    brand: 'Orient',
    countInStock: 14,
    rating: 4.7,
    numReviews: 48,
  },
  {
    name: 'Oris Aquis Date Calibre 400',
    price: 285000,
    description: "High-performance automatic diver featuring Oris's in-house Calibre 400 movement with a 5-day power reserve, anti-magnetic, and a 10-year warranty.",
    images: ['/watch-img/Oris Aquis Date Calibre 400.jpg'],
    category: 'Mechanical',
    brand: 'Oris',
    countInStock: 7,
    rating: 4.6,
    numReviews: 15,
  },
  {
    name: 'Panerai Luminor Marina',
    price: 640000,
    description: 'Distinctive cushion-shaped steel case with the patented crown protection bridge. Features the iconic sandwich dial with small seconds at 9 o\'clock.',
    images: ['/watch-img/Panerai Luminor Marina.jpg'],
    category: 'Luxury',
    brand: 'Panerai',
    countInStock: 3,
    rating: 4.7,
    numReviews: 18,
  },
  {
    name: 'Piaget Altiplano Rose Gold',
    price: 1650000,
    description: 'Master of ultra-thin watchmaking. Elegant 18k rose gold case, clean minimalist dial with thin baton hands and manual-winding mechanical movement.',
    images: ['/watch-img/Piaget Altiplano Rose Gold.jpg'],
    category: 'Luxury',
    brand: 'Piaget',
    countInStock: 2,
    rating: 4.8,
    numReviews: 7,
  },
  {
    name: 'Rado Captain Cook',
    price: 185000,
    description: 'Vintage look with modern high-tech ceramic bezel and sapphire crystal. Automatic movement with 80 hours power reserve and water resistance up to 300m.',
    images: ['/watch-img/Rado Captain Cook.jpg'],
    category: 'Mechanical',
    brand: 'Rado',
    countInStock: 10,
    rating: 4.5,
    numReviews: 29,
  },
  {
    name: 'Tudor Black Bay 58',
    price: 310000,
    description: "A tribute to the brand's first divers' watches. 39mm case, manufacture Calibre MT5402 movement, rivet-style steel bracelet, and matte black dial.",
    images: ['/watch-img/Tudor Black Bay 58.jpg'],
    category: 'For Him',
    brand: 'Tudor',
    countInStock: 5,
    rating: 4.8,
    numReviews: 31,
  },
  {
    name: 'VTech KidiZoom Smartwatch DX3',
    price: 4990,
    description: 'Kid-friendly smartwatch featuring dual cameras for photos/videos, games, voice recorder, customisable clock faces, and active play challenges.',
    images: ['/watch-img/VTech KidiZoom Smartwatch DX3.jpg'],
    category: 'For Kids',
    brand: 'VTech',
    countInStock: 30,
    rating: 4.3,
    numReviews: 54,
  },
  {
    name: 'Vacheron Constantin Overseas',
    price: 2150000,
    description: 'The spirit of travel. Distinctive hexagonal bezel, blue dial, integrated steel bracelet with easy-fit system, and hand-finished automatic calibre.',
    images: ['/watch-img/Vacheron Constantin Overseas.jpg'],
    category: 'Luxury',
    brand: 'Vacheron Constantin',
    countInStock: 2,
    rating: 4.9,
    numReviews: 9,
  },
  {
    name: 'Zenith El Primero Chronomaster',
    price: 820000,
    description: 'Featuring the legendary high-frequency El Primero automatic chronograph movement. Tri-colour dial with 1/10th of a second chronograph display.',
    images: ['/watch-img/Zenith El Primero Chronomaster.jpg'],
    category: 'Mechanical',
    brand: 'Zenith',
    countInStock: 4,
    rating: 4.8,
    numReviews: 20,
  },
];
const connectDB = async () => {
  try {
    const conn = await mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/watchstore');
    console.log(`MongoDB Connected: ${conn.connection.host}`);
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};
const importData = async () => {
  try {
    await connectDB();
    await Order.deleteMany();
    await Product.deleteMany();
    await User.deleteMany();
    for (const u of users) {
      await User.create(u);
    }
    await Product.insertMany(products);
    console.log('Data Imported! — 39 products across 6 categories');
    process.exit();
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};
importData();